spring:
  devtools:
    add-properties: false
  messages:
    basename: message/message
  datasource:
    url: jdbc:mysql://localhost:3306/micro_user
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bike-service
server:
  port: 8003
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
