spring:
  devtools:
    add-properties: false
  messages:
    basename: message/message
  datasource:
    url: jdbc:mysql://localhost:3306/micro_user
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bike-service
server:
  port: 8003
