server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-service
          uri: https://github.com/MichaelSsSs88/Microservices
          search-paths: blob/config-service/config-data
  application:
    name: config-service

